### ISSUE TITLE
cannot install simpleaudio

### ISSUE THREAD

**Issue by Matejmikulas** [p7uverma/bard-chatbot#5]
when i try to install all modules in requirements.txt it says
ERROR: Could not build wheels for simpleaudio, which is required to install pyproject.toml-based projects

what shoud i do?

**Comment by PriyanshuPz** [comment]
What operating system you are using. @Matejmikulas ..

**Comment by Matejmikulas** [comment]
windows 11 home

**Comment by PriyanshuPz** [comment]
Create a virtual environment and try @Matejmikulas ..

**Comment by Matejmikulas** [comment]
I try it on linux and same thing happened

**Comment by PriyanshuPz** [comment]
Try to install latest version.
Or in linux install
 `sudo apt-get install libasound2-dev`

If it works please update and do pull request. 

See this if not fix https://simpleaudio.readthedocs.io/en/latest/installation.html

@Matejmikulas ...
